task: detection

evaluator:
  type: CocoEvaluator
  iou_types: ['bbox', ]

# num_classes: 365
# remap_mscoco_category: False

# num_classes: 91
# remap_mscoco_category: False

num_classes: 80
remap_mscoco_category: True

# TODO: change to your own path
dataset_dir: /workspace/datasets/coco # Thay đổi đường dẫn này
train_image_dir: train2017
train_anno_path: annotations/instances_train2017.json
val_image_dir: val2017 # Giữ nguyên nếu cấu trúc đúng
val_anno_path: annotations/instances_val2017.json # Giữ nguyên nếu cấu trúc đúng
test_image_dir: test2017
test_anno_path: annotations/image_info_test-dev2017.json

train_dataloader: 
  type: DataLoader
  dataset: 
    type: CocoDetection
    img_folder: /workspace/datasets/coco/train2017/
    ann_file: /workspace/datasets/coco/annotations/instances_train2017.json
    return_masks: False
    transforms:
      type: Compose
      ops: ~
  shuffle: True
  num_workers: 0
  drop_last: True 
  collate_fn:
    type: BatchImageCollateFuncion


val_dataloader:
  type: DataLoader
  dataset: 
    type: CocoDetection
    img_folder: /workspace/datasets/coco/val2017/
    ann_file: /workspace/datasets/coco/annotations/instances_val2017.json
    return_masks: False
    transforms:
      type: Compose
      ops: ~ 
  shuffle: False
  num_workers: 0
  drop_last: False
  collate_fn:
    type: BatchImageCollateFuncion
